### PR TITLE
Upgrade Google packages

### PR DESCRIPTION
**Pull request by zeniale**

### CODE REVIEW

**Comment by jbowmanp1107** [comment]
Just curious, what issues were fixed with these updates? I am having issues with Android 12 packages and this library.

**Comment by zeniale** [comment]
@jbowmanp1107 In my case I had problems with all Android devices. After 2/3 days of notifications successfully sent to a device, I started getting the error "Requested entity was not found". Firebase support advised me to update the libraries used. After this update I am no longer getting this error.

**Comment by jbowmanp1107** [comment]
Thanks! I hope this can be merged soon then :). I might be running into the same issue

**Comment by pengham** [comment]
> @jbowmanp1107 In my case I had problems with all Android devices. After 2/3 days of notifications successfully sent to a device, I started getting the error "Requested entity was not found". Firebase support advised me to update the libraries used. After this update I am no longer getting this error.

Hi, is it possible to modify PNMessagingService.android.cs line 9 from [Service] to [Service(Exported = true)]?

**Pull request merged**
